server:
  port: 80
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:db_dev;MODE=MYSQL
  #   username: sa
  #   password:

  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://127.0.0.1:3306/db_dev
  #    username: root
  #    password:

custom:
  fileDirPath: C://learning/Next_Spring
